FROM netroy/ubuntu
MAINTAINER Aditya <aditya@netroy.in>

## Prevent dialogs for apt-get
ENV DEBIAN_FRONTEND noninteractive

## Setup locales
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Default to bash
CMD ["/bin/bash"]